-- ============================================================
-- FAST7 Commercial — MASTER (Company / Super-admin) Database
-- Manages dozens/hundreds of subscriber stores.
-- Each store keeps its data in ITS OWN isolated Supabase project,
-- but the company tracks stores + subscriptions + payment codes here.
--
-- NOTE: Run this script in the COMPANY'S master project in
-- supabase.com -> SQL Editor. NOT in a store project.
-- ============================================================

-- ---------- STORES ----------
-- One row per subscriber store. Contains connection info to the
-- store's OWN isolated Supabase project + ownership/billing info.
create table if not exists public.stores (
  store_id text primary key,                -- e.g. 'default', or generated 'st_xxxxxx'
  name text not null,                       -- store display name
  path_slug text not null unique,           -- /<slug>/index.html for hosting
  owner_name text,
  owner_phone text,
  owner_email text,
  -- connection to THIS store's own (isolated) Supabase project:
  supabase_url text,
  anon_key text,
  write_token text,
  -- optional per-store admin panel access code (kept server-side only;
  -- the storefront verifies against it via verify_store_admin, never sees it)
  admin_code text,
  status text not null default 'active',    -- active | suspended | pending
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists idx_stores_status on public.stores(status);

-- Add the column also to existing installations (safe to re-run)
alter table public.stores add column if not exists admin_code text;

-- ---------- SUBSCRIPTIONS ----------
-- Billing/plan history per store. Latest row = current plan.
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  store_id text not null references public.stores(store_id) on delete cascade,
  plan text not null default 'free',         -- free | monthly | annual | vip
  amount numeric not null default 0,
  status text not null default 'active',     -- active | ended | cancelled | trial
  start_date date not null default current_date,
  end_date date,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_subs_store on public.subscriptions(store_id);
create index if not exists idx_subs_status on public.subscriptions(status);
create index if not exists idx_subs_end   on public.subscriptions(end_date);

-- ---------- PAYMENT / ACTIVATION CODES ----------
-- Codes a store owner enters to activate a plan or pay subscription fees.
create table if not exists public.subscription_codes (
  code text primary key,                    -- e.g. F7-2026-A1B2C3
  store_id text references public.stores(store_id),
  code_type text not null default 'subscription',  -- subscription | fee | credit
  plan text,                                -- for subscription codes
  amount numeric default 0,                 -- for fee codes
  used boolean not null default false,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create index if not exists idx_codes_type on public.subscription_codes(code_type);
create index if not exists idx_codes_used on public.subscription_codes(used);

-- ---------- RLS ----------
-- The master DB is admin-only. Block public writes entirely.
alter table public.stores               enable row level security;
alter table public.subscriptions        enable row level security;
alter table public.subscription_codes   enable row level security;

-- TODO: decide access model. Default = only authenticated (service/admin) can manage.
-- Recommended: create an admin user in Supabase Auth and grant only to it.
drop policy if exists "admin owns stores"              on public.stores;
drop policy if exists "admin owns subscriptions"       on public.subscriptions;
drop policy if exists "admin owns subscription_codes"  on public.subscription_codes;

create policy "admin owns stores"              on public.stores              for all to authenticated using (true) with check (true);
create policy "admin owns subscriptions"       on public.subscriptions       for all to authenticated using (true) with check (true);
create policy "admin owns subscription_codes"  on public.subscription_codes  for all to authenticated using (true) with check (true);

-- ============================================================
-- SAFE PUBLIC READER for stores.
-- The storefront (anon role) needs to know ONLY its own status
-- to auto-suspend itself. This function is SECURITY DEFINER so it
-- bypasses RLS, but returns a single row (the requested store) and
-- no secrets (no anon_key / write_token / owner data).
-- ============================================================
create or replace function public.get_store_status(p_store text)
returns table (status text, suspended boolean)
language sql security definer set search_path = public as $$
  select s.status,
         (s.status = 'suspended') as suspended
  from public.stores s
  where s.store_id = p_store;
$$;
revoke all on function public.get_store_status(text) from public;
grant execute on function public.get_store_status(text) to anon, authenticated;

-- ============================================================
-- SAFE ADMIN CODE CHECK.
-- The storefront NEVER sees the admin code. When a store owner
-- submits a code, the front-end calls this function which returns
-- ONLY a boolean (true/false). SECURITY DEFINER bypasses RLS, but:
--   * takes the code as a parameter (never returns it),
--   * matches against the per-store admin_code column.
-- Setting admin_code is OWNER/COMPANY only (RLS blocks public writes).
-- NOTE: After ALTERing the stores table, re-run this whole script.
-- ============================================================
create or replace function public.verify_store_admin(p_store text, p_code text)
returns boolean
language sql security definer set search_path = public as $$
  select coalesce(
    (select (s.admin_code is not null and s.admin_code = p_code)
       from public.stores s
      where s.store_id = p_store),
    false
  );
$$;
revoke all on function public.verify_store_admin(text, text) from public;
grant execute on function public.verify_store_admin(text, text) to anon, authenticated;